version: '3'

services:
    userdb:
        image: ${USER_DB_IMAGE:-postgres:14.2-alpine}
        container_name: userdbcontainer
        ports:
        - 5436:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        restart: always


    app:
        image: ${USER_SERVICE_IMAGE}
        container_name: userservice_container
        ports:
            - 7777:7777
        environment:
            PASSWORD: ${POSTGRES_PASSWORD}
            USERNAME: ${POSTGRES_USER}
            URL: ${URL}
        depends_on:
            - userdb
        restart: always
