server:
  port: 7777
spring:
  application:
    name: userservice
  datasource:
    password: ${PASSWORD}
    url: ${URL}
    username: ${USERNAME}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

