server:
  port: 7777
spring:
  application:
    name: userservice
  datasource:
    password: ${PASSWORD}
    url: ${URL}
    username: ${USERNAME}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: "livenessstate,db"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true