apiVersion: v1
kind: Namespace
metadata:
  name: epam-mentoring-kuber-namespace
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pv-claim # name of PVC essential for identifying the storage data
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: userdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postdb-pv-claim
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: postdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# Configure 'Deployment' of  server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: userdb
    tier: database
spec:
  selector: # psql Pod Should contain same labels
    matchLabels:
      app: userdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: userdb
        tier: database
    spec:
      containers:
        - image: epamantontsyrkunou/userdb # image from docker
          name: userdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-db-config-map
                  key: POSTGRES_DB_USER
          ports:
            - containerPort: 5437
              name: userdb
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: userdb-pv-claim
              mountPath: /var/lib/psql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: userdb-pv-claim # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: userdb-pv-claim
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postdb
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: postdb
    tier: database
spec:
  selector:
    matchLabels:
      app: postdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postdb
        tier: database
    spec:
      containers:
        - image: epamantontsyrkunou/postdb # image from docker
          name: postdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB # Setting Database Name from a 'ConfigMap'
              valueFrom:
                configMapKeyRef:
                  name: user-db-config-map
                  key: POSTGRES_DB_POST

          ports:
            - containerPort: 5437
              name: postdb
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: postdb-pv-claim
              mountPath: /var/lib/psql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: postdb-pv-claim # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: postdb-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: userdb
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: userdb
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: userdb
    tier: database
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: postdb
  namespace: epam-mentoring-kuber-namespace
  labels:
    app: postdb
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postdb
    tier: database
  clusterIP: None
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  namespace: epam-mentoring-kuber-namespace
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 2
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: epamantontsyrkunou/userservice-1.0.0
          ports:
            - containerPort: 7777
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_PASSWORD

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_USER

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: user-db-config-map
                  key: URL_USER
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice-deployment
  namespace: epam-mentoring-kuber-namespace
spec:
  selector:
    matchLabels:
      app: postservice
  replicas: 2
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: epamantontsyrkunou/postservice-1.0.0
          ports:
            - containerPort: 8888
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_PASSWORD

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: POSTGRES_USER

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: user-db-config-map
                  key: URL_POST

            - name: FEIGN_URL
              valueFrom:
                configMapKeyRef:
                  name: user-db-config-map
                  key: FEIGN_URL
---

apiVersion: v1
kind: Service
metadata:
  name: userservice-svc
  namespace: epam-mentoring-kuber-namespace
spec:
  selector:
    app: userservice
  ports:
    - port: 7777 # The port that the service is running on in the cluster
      targetPort: 7777 # The port exposed by the service
      nodePort: 31515
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: postservice-svc
  namespace: epam-mentoring-kuber-namespace
spec:
  selector:
    app: postservice
  ports:
    - port: 7777 # The port that the service is running on in the cluster
      targetPort: 8888 # The port exposed by the service
      nodePort: 31516 # The TCP port in cluster
  type: NodePort # type of the service.
---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx-example
  namespace: epam-mentoring-kuber-namespace
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: epam-mentoring-kuber-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
          - path: /us/?(.*)
            pathType: Prefix
            backend:
              service:
                name: userservice-svc
                port:
                  number: 7777
          - path: /ps/?(.*)
            pathType: Prefix
            backend:
              service:
                name: postservice-svc
                port:
                  number: 7777
