apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config-map
data:
  POSTGRES_DB_USER : userdb
  POSTGRES_DB_POST: postdb
  URL_USER : jdbc:postgresql://host.docker.internal:5432/userdb
  URL_POST : jdbc:postgresql://host.docker.internal:5432/postdb
  FEIGN_URL: http://10.106.26.72:7777/ # must matches with userservice NodePort cluster ip -> 10.106.26.72  and port ->7777
