
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config-map
    {{- template "mychart.labels" . }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB_USER : userdb
  POSTGRES_DB_POST: postdb
  URL_USER : jdbc:postgresql://10.98.222.203:5432/userdb
  URL_POST : jdbc:postgresql://10.105.76.164:5432/postdb
  FEIGN_URL: http://10.99.31.119:8181/ # must matches with userservice NodePort cluster ip -> 10.106.26.72  and port ->8181
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER : cG9zdGdyZXM=
  POSTGRES_PASSWORD : cG9zdGdyZXM=
---


# USER_DB

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userdb
  namespace: {{ .Values.namespace }}
  labels:
    app: userdb
    tier: database
spec:
  selector:
    matchLabels:
      app: userdb
      tier: database
  serviceName: userdb
  replicas: {{ .Values.stateful.replicas }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: userdb
        tier: database
    spec:
      containers:
        - image: epamantontsyrkunou/userdb # image from docker
          name: userdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config-map
                  key: POSTGRES_DB_USER
          ports:
            - containerPort: 5432
              name: userdb
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: userdb-pv-claim
              mountPath: /var/lib/psql #This is the path in the container on which the mounting will take place.
  volumeClaimTemplates:
    - metadata:
        name: userdb-pv-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-local-userdb-storage"
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: userdb
  namespace: {{ .Values.namespace }}
  labels:
    app: userdb
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: userdb
    tier: database
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-userdb-local
  namespace: epam-mentoring-kuber-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-userdb-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Release.Name }}-postdb-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-postdb-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---

#USER_SERVICES

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: epamantontsyrkunou/userservice-1.0.2
          ports:
            - containerPort: 7777
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_PASSWORD

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_USER

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config-map
                  key: URL_USER
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7777
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7777
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: v1
kind: Service
metadata:
  name: userservice-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: userservice
  ports:
    - port: 8181 # The port that the service is running on in the cluster
      targetPort: 7777 # The port exposed by the service
      nodePort: {{ .Values.userservice.port }}
  type: NodePort
---


# POST_DB

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postdb
  namespace: {{ .Values.namespace }}
  labels:
    app: postdb
    tier: database
spec:
  selector:
    matchLabels:
      app: postdb
      tier: database
  serviceName: postdb
  replicas: {{ .Values.stateful.replicas }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postdb
        tier: database
    spec:
      containers:
        - image: epamantontsyrkunou/postdb # image from docker
          name: postdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config-map
                  key: POSTGRES_DB_POST
          ports:
            - containerPort: 5432
              name: postdb
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: postdb-pv-claim
              mountPath: /var/lib/psql #This is the path in the container on which the mounting will take place.
  volumeClaimTemplates:
    - metadata:
        name: postdb-pv-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-local-postdb-storage"
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: postdb
  namespace: {{ .Values.namespace }}
  labels:
    app: postdb
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postdb
    tier: database
---

#POST_SERVICES

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postservice
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: epamantontsyrkunou/postservice-1.0.3
          ports:
            - containerPort: 8888
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_PASSWORD

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: POSTGRES_USER

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config-map
                  key: URL_POST

            - name: FEIGN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-config-map
                  key: FEIGN_URL
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: v1
kind: Service
metadata:
  name: postservice-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postservice
  ports:
    - port: 8181 # The port that the service is running on in the cluster
      targetPort: 8888 # The port exposed by the service
      nodePort: {{ .Values.postservice.port }} # The TCP port in cluster
  type: NodePort
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
#  ingressClassName: nginx-example
  rules:
    - http:
        paths:
          - path: /uss/?(.*)
            pathType: Prefix
            backend:
              service:
                name: userservice-svc
                port:
                  number: 8181
          - path: /pss/?(.*)
            pathType: Prefix
            backend:
              service:
                name: postservice-svc
                port:
                  number: 8181

---